services:

  db:
    image: mariadb:latest
    container_name: mauticdb
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=mautic
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=secret

  mautic:
    image: mautic/mautic:latest
    container_name: mautic
    volumes:
      - ./mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=db:3306
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=secret
      - MAUTIC_DB_NAME=mautic
    depends_on:
      - db     
    restart: unless-stopped
    ports:
      - "8200:80"
